version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker-prod.dockerfile
    environment:
      VIRTUAL_HOST: "vue-store.do.tahsinature.me"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "vue-store.do.tahsinature.me"
    networks:
      - nginx_proxy_net

networks:
  nginx_proxy_net:
    external: true