version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker-prod.dockerfile
    ports:
      - "80"
      - "443"
    environment:
      VIRTUAL_HOST: "vue-store.do.tahsinature.me"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "vue-store.do.tahsinature.me"

