version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker-prod.dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.vue-store-client.rule=Host(`vue-store.tahsin.us`)
      - traefik.http.routers.vue-store-client.entrypoints=websecure
      - traefik.http.services.vue-store-client.loadbalancer.server.port=80
      - traefik.http.routers.vue-store-client.tls=true
      - traefik.http.routers.vue-store-client.tls.certresolver=myresolver
    networks:
      - traefik

networks:
  traefik:
    external: true